import { defineHandler, defineRouteMeta, HTTPError } from "nitro";
import { getQuery, getRouterParam, redirect } from "nitro/h3";
import { eq } from "drizzle-orm";
import { db } from "~/server/utils/db/config";
import { accounts, users } from "~/server/utils/db/schema";
import { env } from "~/server/utils/env";
import { createSession } from "~/server/utils/auth";
import { oauthProviders } from "~/server/utils/oauth";

defineRouteMeta({
  openAPI: {
    tags: ["oauth"],
    summary: "OAuth callback",
    description:
      "Exchanges the authorization code (with the PKCE verifier) for tokens, finds or creates the user + account, then signs the user in and redirects to the app.",
    parameters: [
      {
        in: "query",
        name: "code",
        required: true,
        description: "Authorization code returned by the provider",
        schema: { type: "string" },
      },
      {
        in: "query",
        name: "code_verifier",
        required: true,
        description: "PKCE code verifier generated by the client",
        schema: { type: "string" },
      },
    ],
    responses: {
      302: { description: "Redirect to the app URL after successful sign-in" },
      400: { description: "Missing code or code_verifier parameter" },
      404: { description: "Unknown OAuth provider" },
    },
  },
});

/**
 * OAuth callback: exchanges the authorization code (with the PKCE verifier)
 * for tokens, finds or creates the user + account, then signs the user in.
 *
 * The client starts the flow (builds the authorization URL with a PKCE
 * challenge and a `state`), and the provider redirects back here with
 * `code` + `state`. The client must supply the matching `code_verifier`.
 */
export default defineHandler(async (event) => {
  const providerId = getRouterParam(event, "provider");
  const provider = providerId ? oauthProviders[providerId] : undefined;
  if (!provider) {
    throw new HTTPError(`Unknown OAuth provider: ${providerId}`, {
      status: 404,
    });
  }

  const query = getQuery(event);
  const { code, code_verifier: codeVerifier } = query;
  if (typeof code !== "string" || typeof codeVerifier !== "string") {
    throw new HTTPError("Missing code or code_verifier parameter", {
      status: 400,
    });
  }

  const tokens = await provider.exchangeCode(code, codeVerifier);
  const userInfo = await provider.getUserInfo(tokens.accessToken);

  // Find or create the user
  let user = await db.query.users.findFirst({
    where: { email: userInfo.email },
  });
  if (!user) {
    user = (
      await db
        .insert(users)
        .values({
          name: userInfo.name,
          email: userInfo.email,
          emailVerified: userInfo.emailVerified,
          image: userInfo.image ?? null,
        })
        .returning()
    )[0];
  }

  // Find or create the provider account, and refresh its tokens
  const existingAccount = await db.query.accounts.findFirst({
    where: { providerId: provider.id, accountId: userInfo.providerId },
  });

  if (!existingAccount) {
    await db.insert(accounts).values({
      userId: user.id,
      accountId: userInfo.providerId,
      providerId: provider.id,
      accessToken: tokens.accessToken,
      refreshToken: tokens.refreshToken ?? null,
      accessTokenExpiresAt: tokens.accessTokenExpiresAt ?? null,
      refreshTokenExpiresAt: tokens.refreshTokenExpiresAt ?? null,
      scope: tokens.scope ?? null,
      idToken: tokens.idToken ?? null,
    });
  } else {
    await db
      .update(accounts)
      .set({
        accessToken: tokens.accessToken,
        refreshToken: tokens.refreshToken ?? existingAccount.refreshToken,
        accessTokenExpiresAt:
          tokens.accessTokenExpiresAt ?? existingAccount.accessTokenExpiresAt,
        refreshTokenExpiresAt:
          tokens.refreshTokenExpiresAt ?? existingAccount.refreshTokenExpiresAt,
        scope: tokens.scope ?? existingAccount.scope,
        idToken: tokens.idToken ?? existingAccount.idToken,
      })
      .where(eq(accounts.id, existingAccount.id));
  }

  await createSession(event, user.id);

  return redirect(env.APP_URL);
});
